image: docker:latest

services:
  - docker:dind

build:
  stage: build
  tags:
    - privileged
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID"
    - docker tag "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"